version: '3.8'

services:
  # データベース
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    networks:
      - backend
    ports:
      - "5432:5432"

  # バックエンドAPI
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
    restart: always
    depends_on:
      - db
    networks:
      - backend
      - frontend
    ports:
      - "8000:8000"

  # フロントエンド
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://${DOMAIN}:8000
    restart: always
    depends_on:
      - api
    networks:
      - frontend
    ports:
      - "3000:3000"

  # リバースプロキシ
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./frontend/public:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - web
    networks:
      - frontend
    restart: always

  # MinIOストレージ (S3互換のオブジェクトストレージ)
  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    env_file:
      - ./.env
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - backend
    restart: always

networks:
  frontend:
  backend:

volumes:
  postgres_data:
  minio_data:
